### ISSUE TITLE
Homestead-prov overloads upon sudden several requests

### ISSUE THREAD

**Issue by chriscoomber** [Metaswitch/crest#244] opened 2015-09-23 17:50 UTC
If you suddenly send several requests to homestead-prov (after a period of not sending very many), it will reject some of them due to overload. Our scenario was to suddenly get ellis to provision 5 numbers at once.

Impact: 
- Ellis' back out may fail, since it chains many requests together here.
- Can't provision 5 numbers at once

This was caused by the bucket being too small for these sudden requests.
Our (coco team's) quick fix (I'm not suggesting this is a proper fix) which worked for us is: in src/metaswitch/crest/api/base.py, change line:
`loadmonitor = LoadMonitor(0.1, 20, 10, 10)`
to
`loadmonitor = LoadMonitor(0.1, 100, 100, 40)`

**Comment by johadalin** [comment] 2017-01-19 14:14
This is fixed by #329 , as well as improving our load monitoring behaviour in crest. 

Passing over to @rkd-msw , as i don't know if we've ever done testing of overload in homestead prov. I'm happy that this issue is fixed, and can be closed down at any point, but you may want to do some proper stress testing on multicore VMs etc. to make sure there aren't any conditions we miss.

**Comment by rkd-msw** [comment] 2017-01-27 17:19
I'm not able to reproduce this (even without your fix on 10.0.0-170106-~255.00.0-170106.020448) - I've tried running `/usr/share/clearwater/bin/create_user` to create 2,000 users, and run four copies of that in parallel, but no requests seem to fail due to overload, and all 8,000 users were created successfully after about 10 minutes.

**Comment by rkd-msw** [comment] 2017-01-27 17:22
Actually I probably can't reproduce it because this system has been up for a while and the rate gradually crept up. I'll try with your fix on a freshly-restarted system.

**Comment by johadalin** [comment] 2017-01-27 17:23
:+1:

**Comment by rkd-msw** [comment] 2017-01-30 22:16
I've successfully created 100,000 users and then updated all their IFCs on 10.0.0-170127-~255.00.0-170127.020342, so I'm happy that there are no issues with homestead-prov getting overloaded.

**Closed by rkd-msw** 2017-01-30 22:16 UTC
Labels: bug, critical, medium-priority
